### ISSUE TITLE
Metadata warning is logged when Pacemaker starts

### ISSUE THREAD

**Issue by jcharaoui** [digimer/fence_delay#1]
These errors show up in our logs when the `fence_delay` agent is active. It doesn't seem to impact the normal operation of the agent or the cluster.

```
pacemaker-controld[2392]:  notice: Requesting local execution of probe operation for p_fence_delay on scgaia00
pacemaker-controld[2392]:  warning: Metadata action for fence_delay failed: Generic Pacemaker error
pacemaker-controld[2392]:  warning: Failed to get metadata for p_fence_delay (stonith:(null):fence_delay)
pacemaker-controld[2392]:  warning: Metadata action for fence_delay failed: Generic Pacemaker error
pacemaker-controld[2392]:  warning: Failed to get metadata for p_fence_delay (stonith:(null):fence_delay)
pacemaker-controld[2392]:  notice: Result of probe operation for p_fence_delay on scgaia00: not running
```

**Comment by jcharaoui** [comment]
~~I think I fixed this by removing `op monitor interval=60m` from the resource config.~~ Nope.

**Comment by digimer** [comment]
Thanks for this. If/when you find the fix, I'll merge.

**Comment by jcharaoui** [comment]
It seems I was able to fix this by deleting the log file at `/var/log/fence_delay.log`.

I'm unsure what the ownership and permissions were before, but now owner/group is `root` with perms `-rw-r-----` and starting/stopping the fence resource no longer causes the warnings.

**Comment by jcharaoui** [comment]
Reopening because after rebooting the node, the error is back! It's a really weird issue...

**Comment by jcharaoui** [comment]
For the record, this is using Pacemaker 2.0.5 on Debian 11.

**Comment by digimer** [comment]
I've never tested this on Debian. If you find the problem though, I'll be happy to pull merge a PR.

**Comment by jcharaoui** [comment]
I wish I knew enough Perl to test a modified version with logging to file switched off. Somehow I think its related to that.

**Comment by jcharaoui** [comment]
Alright so I was able to reproduce the error reliably: Pacemaker needed to restart in order for it to call the metadata op (restarting the resource wasn't enough). After a bit of testing I found that the error went away for good when ownership of the log file was set to `hacluster:haclient` instead of `root:root`.

**Comment by digimer** [comment]
Excellent, thank you. I can probably update fence_delay to set the ownership directly.

**Comment by digimer** [comment]
This should hopefully be resolved now. Please note that current / future dev on fence_delay will by on the anvil repo - https://github.com/ClusterLabs/anvil/blob/master/tools/fence_delay

If the problem persists, please open an issue over there.
